spring:
  application:
    name: usuarios-service

  datasource:
    url: jdbc:postgresql://postgres:5432/BD_Rocky_Usuarios
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

server:
  port: 0
